#
# Blog Settings
#
author: Jianghao Lu
description: Jianghao's Cosmos
url: http://blog.jianghaolu.com
title: Jianghao's Cosmos
subtitle: 西雅图的小宇宙
gravatar_url: https://avatars2.githubusercontent.com/u/2320445

# Github repositories
github_user: jianghaolu
github_repo_url: https://github.com/jianghaolu/life_blog/

kramdown:
  hard_wrap: false

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
